### ISSUE TITLE
Html docs for Karma:Iterator Based Generator API reference dead SGI link for OutputIterator

### ISSUE THREAD

**Issue by jdmairs** [boostorg/spirit#382]
Instead of using a std::string with a back_inserter I'm trying to use a Microsoft Gudeline Support Library (GSL) string_span.  A string_span<> is basically a pointer and a length that allows safer buffer manipulation.

**Comment by Kojoley** [comment]
Dead SGI link fixed in #372.


To use a `gsl::string_span` with Karma you need to write an output iterator. Alternatively you can use `boost::iostreams::stream<boost::iostreams::array_sink>` to wrap the span into a stream and construct an iterator from it with `boost::spirit::ostream_iterator`.

Example:
```cpp
#include <vector>
#include <gsl/string_span>
#include <boost/spirit/include/karma.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/stream.hpp>

int main()
{
    std::vector<char> vec(5);
    gsl::string_span<> span{vec};

    boost::iostreams::stream<boost::iostreams::array_sink> stream(span.data(), span.size());
    boost::spirit::ostream_iterator sink(stream);
    boost::spirit::karma::generate(sink, ...);
}
```
