### ISSUE TITLE
crash when expecting a std::string literal

### ISSUE THREAD

**Issue by dvirtz** [boostorg/spirit#391]
https://wandbox.org/permlink/qSp4Kkb1bLd5rl0u:
```c++
#include <boost/spirit/home/x3.hpp>
namespace x3 = boost::spirit::x3;

auto parser() {
    std::string b = "5";
    return x3::eps > b;
}

int main() {
    std::string input = "5";
    assert(x3::parse(input.begin(), input.end(), parser()));
}
```

```
terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::spirit::x3::expectation_failure<std::__1::__wrap_iter<char*> > > >: boost::spirit::x3::expectation_failure
```

It seems the cause is at https://github.com/boostorg/spirit/blob/b023ffa272b115815b6e714f8cc43bb9e09a9e14/include/boost/spirit/home/x3/string/literal_string.hpp#L231 where it should be `std::basic_string<Char>` instead of `Char const*`, as currently the parser stores a pointer to the string buffer which goes out of scope.

The same code passes without problems with qi: https://wandbox.org/permlink/6xLC19SSZXQXjCp5

**Comment by Kojoley** [comment]
> it should be `std::basic_string<Char>` instead of `Char const*`

No, it must not. At least not in your example (see explanation in the end).

> currently the parser stores a pointer to the string buffer

That's right.

> which goes out of scope.

Not the pointer, but the string itself.

Recap: You are binding to a temporary string that will be out of scope (already destroyed) by the time when you are invoking the parser. With Qi you have the same bug in your program, but do not observe the problem just by luck. It is your fault, and unfortunately compilers do not do deep object lifetime analysis (it can change in future, see Herb Sutter talk), but you can use [AddressSanitize](https://github.com/google/sanitizers/wiki/AddressSanitizerUseAfterScope) to catch those bugs at run-time.

Rationale: If you are passing a string object to Spirit it has to be generated at run-time and most of the users obviously do not want to have unneeded copy operation (that's why I am sure that #175 was wrong).

Probably, we should move-in and store user string if it was passed by rvalue, but you did not pass your string as an rvalue.
